name: pathplanner
description: A simple yet powerful motion profile generator for FRC robots

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 25.2.3+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  shared_preferences: ^2.3.2
  file_selector: ^1.0.3
  undo: ^1.5.0
  visibility_detector: ^0.4.0+2
  github: ^9.24.0
  version: ^3.0.2
  url_launcher: ^6.3.0
  macos_secure_bookmarks: ^0.2.1
  function_tree: ^0.9.1
  path_provider: ^2.1.4
  image_size_getter: ^2.1.3
  path: ^1.9.0
  window_manager: ^0.4.2
  flutter_colorpicker: ^1.1.0
  logger: ^2.4.0
  http: ^1.2.2
  fl_chart: ^0.69.0
  package_info_plus: ^8.0.2
  multi_split_view: ^2.4.0
  file: ^7.0.0
  collection: ^1.18.0
  nt4: ^1.3.3
  flutter_animate: ^4.5.0
  watcher: ^1.1.0
  matrices: ^1.2.7
  scidart: ^0.0.2-dev.12
  dropdown_button2: ^2.3.9
  isolate_manager: ^5.4.0
  widgets_to_image: ^1.0.0
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  full_coverage: ^1.0.0
  msix: ^3.16.8
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.12
  cider: ^0.2.8
  inno_bundle: ^0.8.0


inno_bundle:
  id: f887e5f0-4690-1e07-8efc-a12ea7711afb # <-- Put your app id here
  publisher: YCY # Optional, but recommended.
  name: FRC PathPlanner for Lvlib24 # 
  admin: auto
  languages:
    - english
  installer_icon: images/icon-64.ico


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - resources/default_navgrid.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  display_name: FRC PathPlanner
  publisher_display_name: Michael Jansen
  identity_name: 39956MichaelJansen.FRCPathPlanner
  publisher: CN=2DF9861F-6D68-40A5-BCD2-A0BC837334E3
  logo_path: windows/icon.png
  languages: en-us
  icons_background_color: transparent
  capabilities: internetClient, privateNetworkClientServer 
