name: Run Tests

on:
  push:
    branches: [main]

  pull_request:
  
  workflow_dispatch:

jobs:
  dart-formatting:
    name: Check Dart Formatting & Analysis
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.8
          cache: true
          cache-path: ${{ runner.tool_cache }}/flutter/linux
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Analyze
        run: flutter analyze
      
      - name: Check formatting
        run: flutter format -o none --set-exit-if-changed lib/* test/*
  
  pplib-formatting:
    name: Check PathPlannerLib Formatting
    runs-on: ubuntu-22.04
    container: wpilib/ubuntu-base:22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./pathplannerlib
      
      - name: Check formatting
        run: ./gradlew spotlessCheck
        working-directory: ./pathplannerlib
  
  flutter-tests:
    name: Flutter Tests
    runs-on: ubuntu-22.04
    needs: [dart-formatting]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.8
          cache: true
          cache-path: ${{ runner.tool_cache }}/flutter/linux

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
  
  pplib_tests:
    name: PathPlannerLib Tests
    runs-on: ubuntu-22.04
    needs: [pplib-formatting]
    container: wpilib/roborio-cross-ubuntu:2023-22.04
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./pathplannerlib
        
      - name: Compile and run tests
        run: ./gradlew build -PreleaseMode
        working-directory: ./pathplannerlib
